export { default as Events } from "./Events";
export { default as Home } from "./Home";
export { default as Scheduling } from "./Scheduling";
export { default as Documents } from "./Documents";
export { default as Auth } from "./Auth";
export { default as Search } from "./Search";
export { default as RegisterAccount } from "./RegisterAccount";
export { default as Chat } from "./Chat";
export { default as BrgyCertificate } from "./BrgyCertificate";