export const Payawan1 = [
  "ALL",
  "PUROK 1",
  "PUROK 2",
  "PUROK 3",
  "PUROK 4",
  "PUROK 5",
];
export const Payawan2 = [
  "ALL",
  "PUROK 6",
  "PUROK 7",
  "PUROK 8",
  "PUROK 9 ILANG-ILANG",
  "PUROK 10 SPRINGVILLE A",
  "PUROK 11 SPRINGVILLE B",
  "PUROK 11 SPRINGVILLE C",
  "PUROK 12 MACRESIA/GREENHOMES",
  "PUROK 34 MUSLIM COMMUNITY",
];
export const CentralPoblacion = [
  "ALL",
  "PUROK 17 POBLACION 2",
  "PUROK 18 RIVCOR POBLACION",
  "PUROK 22 HOLY CROSS/ NEMBUSCO",
  "PUROK 20 POBLACION 3",
  "PUROK 21 AIRPORT RIVERSIDE",
  "PUROK 19 TUAZON VILLAGE",
];
export const Bacud = [
  "ALL",
  "PUROK 29 HIGHWAY BACUD",
  "PUROK 30 INTERIOR",
  "PUROK 31 PANGPANG RIVERSIDE",
  "PUROK 32 CORTES",
];
export const SanVicente = ["ALL", "PUROK 33", "PUROK 33-A"];
export const Looc = [
  "ALL",
  "PUROK 23",
  "PUROK 24",
  "PUROK 24-A",
  "PUROK 25 MAGBAGO",
  "PUROK 26 GK/EXIT",
];
export const Bernadette = [
  "ALL",
  "PUROK 14",
  "PUROK 15",
  "PUROK 16",
  "PUROK 20",
  "PUROK 5",
];
export const Toril = [
  "ALL",
  "PUROK 27",
  "PUROK 27-A",
  "PUROK 28",
  "PUROK 28-A",
];

export const populace = [
  {
    id: 1,
    image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
    lastName: "Gahagan",
    firstName: "Si",
    middleName: "Hélène",
    suffix: "Jr",
    address: "Purok 1, Payawan 1",
    dateOfBirth: "4/28/2006",
    placeOfBirth: "Sułoszowa",
    sex: "Male",
    civilStatus: "DIvorced",
    nameOfParents: "Jose Franklin Ajo, Cherlie Tulang Ajo",
    nameOfSiblings: "Stefhanie Ajo, Michelle May Ajo, Jamesmar Ajo",
    citizenship: "Salvadoran",
    occupation: "Staff Scientist",
    isPWD: true,
    is4ps: true,
    isRegVoter: true,
    occupancyStatus: "House Owner",
  },
  {
    id: 2,
    image: "http://dummyimage.com/211x100.png/dddddd/000000",
    lastName: "Bodesson",
    firstName: "Claudell",
    middleName: "Åslög",
    address: "Purok 7, Payawan 2",
    placeOfBirth: "Aţ Ţawāḩīn",
    dateOfBirth: "2/7/2009",
    sex: "Male",
    civilStatus: "Separated",
    citizenship: "Chilean",
    occupation: "Statistician IV",
    isPWD: false,
    is4ps: false,
    isRegVoter: false,
    occupancyStatus: "House Owner",
  },
  {
    id: 3,
    image: "http://dummyimage.com/217x100.png/dddddd/000000",
    lastName: "Breed",
    firstName: "Albertine",
    middleName: "Mélys",
    address: "Purok 19 Tuazon Village, Central Poblacion",
    placeOfBirth: "Cortes",
    dateOfBirth: "10/15/1981",
    sex: "Female",
    civilStatus: "Single",
    citizenship: "Black or African American",
    occupation: "Actuary",
    isPWD: true,
    is4ps: false,
    isRegVoter: true,
    occupancyStatus: "Renter",
  },
  {
    id: 4,
    image: "http://dummyimage.com/194x100.png/dddddd/000000",
    lastName: "Ibel",
    firstName: "Robers",
    middleName: "Séverine",
    address: "Purok 30 Interior, Bacud",
    placeOfBirth: "Syrskoye",
    dateOfBirth: "3/14/2015",
    sex: "Male",
    civilStatus: "Single",
    citizenship: "Salvadoran",
    occupation: "Automation Specialist III",
    isPWD: false,
    is4ps: true,
    isRegVoter: false,
    occupancyStatus: "Renter",
  },
  {
    id: 5,
    image: "http://dummyimage.com/174x100.png/ff4444/ffffff",
    lastName: "Harris",
    firstName: "Rebecca",
    middleName: "Géraldine",
    address: "PUROK 33, SAN VICENTE",
    placeOfBirth: "Maqiu",
    dateOfBirth: "2/13/1961",
    sex: "Female",
    civilStatus: "DIvorced",
    citizenship: "Colville",
    occupation: "Data Coordiator",
    isPWD: false,
    is4ps: false,
    isRegVoter: false,
    occupancyStatus: "Sharer",
  },
  {
    id: 6,
    image: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
    lastName: "Anthonies",
    firstName: "Terrijo",
    middleName: "Simplifiés",
    address: "PUROK 24, LOOC",
    placeOfBirth: "Yuanguping",
    dateOfBirth: "2/1/1993",
    sex: "Female",
    civilStatus: "Married",
    citizenship: "Panamanian",
    occupation: "Operator",
    isPWD: true,
    is4ps: true,
    isRegVoter: true,
    occupancyStatus: "House Owner",
  },
  {
    id: 7,
    image: "http://dummyimage.com/225x100.png/ff4444/ffffff",
    lastName: "McIlrath",
    firstName: "Horace",
    middleName: "Anaé",
    address: "PUROK 14, BERNADETTE",
    placeOfBirth: "Stockholm",
    dateOfBirth: "1/25/1954",
    sex: "Male",
    civilStatus: "Widow",
    citizenship: "Polynesian",
    occupation: "Data Coordiator",
    isPWD: false,
    is4ps: true,
    isRegVoter: true,
    occupancyStatus: "Sharer",
  },
  {
    id: 8,
    image: "http://dummyimage.com/225x100.png/5fa2dd/ffffff",
    lastName: "Isselee",
    firstName: "Jessa",
    middleName: "Aloïs",
    address: "PUROK 27, TORIL",
    placeOfBirth: "Jiaogong",
    dateOfBirth: "7/28/2005",
    sex: "Female",
    civilStatus: "DIvorced",
    citizenship: "Central American",
    occupation: "Project Manager",
    isPWD: false,
    is4ps: true,
    isRegVoter: true,
    occupancyStatus: "Sharer",
  },
  {
    id: 9,
    image: "http://dummyimage.com/189x100.png/dddddd/000000",
    lastName: "Hanaby",
    firstName: "Adlai",
    middleName: "Gwenaëlle",
    address: "PUROK 2, PAYAWAN 1",
    placeOfBirth: "Nerekhta",
    dateOfBirth: "12/18/1979",
    sex: "Male",
    civilStatus: "DIvorced",
    citizenship: "Houma",
    occupation: "Occupational Therapist",
    isPWD: true,
    is4ps: true,
    isRegVoter: true,
    occupancyStatus: "Renter",
  },
  {
    id: 10,
    image: "http://dummyimage.com/111x100.png/ff4444/ffffff",
    lastName: "Garley",
    firstName: "Donia",
    middleName: "Bécassine",
    address: "PUROK 3, PAYAWAN 1",
    placeOfBirth: "Los Tangos",
    dateOfBirth: "5/25/1970",
    sex: "Female",
    civilStatus: "Widow",
    citizenship: "Choctaw",
    occupation: "Geologist III",
    isPWD: false,
    is4ps: true,
    isRegVoter: false,
    occupancyStatus: "Renter",
  },
];

export const samplepopulace = {
  id: 1,
  image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  lastName: "Gahagan",
  firstName: "Si",
  middleName: "Hélène",
  suffix: "Jr",
  address: "Purok 1, Payawan 1",
  dateOfBirth: "4/28/2006",
  placeOfBirth: "Sułoszowa",
  sex: "Male",
  civilStatus: "DIvorced",
  nameOfParents: "Jose Franklin Ajo, Cherlie Tulang Ajo",
  nameOfSiblings: "Stefhanie Ajo, Michelle May Ajo, Jamesmar Ajo",
  citizenship: "Salvadoran",
  occupation: "Staff Scientist",
  isPWD: "yes",
  is4ps: "yes",
  isRegVoter: "yes",
  occupancyStatus: "House Owner",
};
